---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: www-deployment
 namespace: default
spec:
 selector:
  matchLabels:
   app: nginx_1
 replicas: 4
 template:
  metadata:
   labels:
    app: nginx_1
  spec:
   containers:
   - name: nginx
     image: nginx:latest
     ports:
     - containerPort: 80
