name: Build and Deploy

on:
  push:
jobs:
  deploy_to_kubernetes_cluster:
    name: Deploy to Kubernetes Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
         k8s-url: http://tassk3s.duckdns.org:8031
         k8s-secret: ${{ secrets.KUBE_CONFIG }} # token value from the result of the below script
        id: login
      - name: Deploy to Cluster
        run: |
          kubectl get deployments --all-namespaces
