name: Build and Deploy

on:
  push:
jobs:
  deploy_to_kubernetes_cluster:
    name: Deploy to Kubernetes Cluster
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set Kubernetes Context
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods

