name: Build and Deploy

on:
  push:
jobs:
  deploy_to_kubernetes_cluster:
    name: Deploy to Kubernetes Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
         method: kubeconfig
         kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Deploy to Cluster
        run: |
          kubectl get deployments --all-namespaces
