name: Build and Deploy

on:
  push:

jobs:
  deploy_to_kubernetes_cluster:
    name: Deploy to Kubernetes Cluster
    needs: push_docker_image_to_github_packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
      - name: Deploy to Cluster
        run: |
          kubectl get pods
